### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by Akbar-arm** [varigit/meta-variscite-hab#1]
There is no overall LICENSE file in this layer. Is it possible to list all the licenses that are used by recipes in this layer?

**Comment by nsdrude** [comment]
@Akbar-arm have you seen https://github.com/varigit/meta-variscite-hab/commit/8ecd0e6d90c9809369f3dddec593da5b795eae1a?

**Comment by Akbar-arm** [comment]
Ah thank you, I was looking at the default branch.
